#!/usr/bin/env bash
# configures a load balancer

# Installing HAproxy on a server
sudo apt-get update
sudo apt install haproxy

# Configure haproxy configuration file
echo '
frontend ai-mron.tech
        bind 0:80
        default_backend my_servers

backend my_servers
        balance roundrobin
        server 64820-web-01 35.153.52.126:80
        server 64820-web-02 100.25.139.140:80
' | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy
sudo service haproxy restart
